# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch
random = torch.rand(7,7)
random

tensor([[0.4774, 0.0078, 0.4623, 0.7985, 0.0484, 0.0880, 0.5790],
        [0.3643, 0.0577, 0.0213, 0.5387, 0.0557, 0.1348, 0.9809],
        [0.0082, 0.5276, 0.1401, 0.9189, 0.7939, 0.6126, 0.5422],
        [0.2510, 0.6510, 0.1271, 0.3336, 0.8106, 0.1245, 0.7050],
        [0.8903, 0.8617, 0.8943, 0.0993, 0.8056, 0.2739, 0.5245],
        [0.8181, 0.8741, 0.7313, 0.5876, 0.3145, 0.7763, 0.1219],
        [0.2175, 0.0300, 0.8465, 0.1493, 0.9137, 0.6569, 0.3104]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
second = torch.rand(7,7)
random @ second.T

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(22)
first = torch.rand(7,7)
torch.manual_seed(22)
second = torch.rand(7,7)

first @ second

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
seed = 1234

torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

# Optional but recommended for deterministic behavior
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
torch.manual_seed(1234)

# Create two random tensors
tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(2, 3)

# Send tensors to GPU (if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_1 = tensor_1.to(device)
tensor_2 = tensor_2.to(device)

# Print results
print(tensor_1)
print(tensor_2)
print("Device:", tensor_1.device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B

output = torch.matmul(tensor_1, tensor_2.T)
output, output.shape

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(output.max())
# Find min
print(output.min())

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(output.argmax())

# Find arg min
print(output.argmin())


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
torch.manual_seed(22)
x = torch.randn(1, 1, 1, 1, 10)
x = x.squeeze(0)
print(x.shape)