# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch
random = torch.rand(7,7)
random

tensor([[0.4301, 0.6007, 0.6402, 0.1818, 0.6165, 0.3434, 0.4159],
        [0.6938, 0.6911, 0.8323, 0.7701, 0.7176, 0.9154, 0.7839],
        [0.6234, 0.2070, 0.4227, 0.8106, 0.2903, 0.8231, 0.1657],
        [0.2684, 0.5386, 0.8776, 0.4331, 0.1554, 0.2107, 0.9897],
        [0.6435, 0.2131, 0.2198, 0.3095, 0.2501, 0.6251, 0.3241],
        [0.1967, 0.4267, 0.1561, 0.0271, 0.8381, 0.2267, 0.5630],
        [0.9404, 0.5122, 0.3647, 0.7363, 0.9513, 0.4793, 0.9008]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
second = torch.rand(7,7)
random @ second.T

tensor([[0.9597, 1.0551, 1.8236, 0.8580, 1.0803, 1.5843, 1.4256],
        [1.7249, 2.0870, 3.2682, 1.4805, 1.7345, 2.6119, 2.4904],
        [1.1388, 1.3840, 2.0486, 0.8032, 1.0983, 1.5645, 1.4801],
        [1.0860, 1.4577, 2.3495, 1.0621, 0.8546, 1.5841, 2.0287],
        [0.8372, 1.0663, 1.5360, 0.6880, 0.9853, 1.2105, 1.0481],
        [0.6074, 0.8099, 1.2706, 0.7806, 0.9543, 1.3152, 0.9715],
        [1.1867, 2.0165, 2.9030, 1.3445, 1.7666, 2.3366, 2.2993]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(22)
first = torch.rand(7,7)
torch.manual_seed(22)
second = torch.rand(7,7)

first @ second

tensor([[1.3756, 1.7253, 1.2846, 1.1073, 1.9839, 1.4216, 1.2049],
        [2.0838, 2.6685, 1.9434, 1.5284, 2.8474, 1.6906, 1.8128],
        [2.1476, 2.9696, 2.1500, 1.5655, 3.2834, 2.2355, 2.1521],
        [1.6524, 2.2837, 1.5294, 1.2874, 2.4569, 1.7887, 1.3379],
        [1.1548, 1.4586, 0.9252, 0.7366, 1.6186, 1.0387, 1.0814],
        [0.9586, 1.3981, 1.0216, 0.7806, 1.4331, 1.0299, 0.5403],
        [0.9134, 1.4645, 0.9219, 0.7321, 1.5804, 1.3314, 0.8200]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
seed = 1234

torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

# Optional but recommended for deterministic behavior
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
torch.manual_seed(1234)

# Create two random tensors
tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(2, 3)

# Send tensors to GPU (if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_1 = tensor_1.to(device)
tensor_2 = tensor_2.to(device)

# Print results
print(tensor_1)
print(tensor_2)
print("Device:", tensor_1.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
Device: cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B

output = torch.matmul(tensor_1, tensor_2.T)
output, output.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print(output.max())
# Find min
print(output.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(output.argmax())

# Find arg min
print(output.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
torch.manual_seed(22)
x = torch.randn(1, 1, 1, 1, 10)
x = x.squeeze(0)
print(x.shape)

torch.Size([1, 1, 1, 10])
