## Check Version

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


## Check GPU

In [2]:
if torch.cuda.is_available():
    print('GPU is Available!')
    print(f"Using GPU {torch.cuda.get_device_name()}")
else:
    print('We are Use Cpu')

GPU is Available!
Using GPU NVIDIA GeForce RTX 3050 6GB Laptop GPU


# Creating a Tensor

In [3]:
torch.empty(3, 4)

tensor([[1.1338e+23, 1.8441e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

## Type of torch

In [4]:
a = torch.empty(3, 4)
print(a.type())
type(a)

torch.FloatTensor


torch.Tensor

## Using Zeros

In [5]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

## Using Rand

In [7]:
torch.rand(3, 4)

tensor([[0.9230, 0.2216, 0.6427, 0.3335],
        [0.3861, 0.4352, 0.3326, 0.3334],
        [0.6638, 0.8398, 0.2061, 0.5817]])

## Manual Seed

In [8]:
torch.manual_seed(100)
torch.rand(3, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [9]:
torch.manual_seed(100)
torch.rand(3, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [10]:
torch.tensor([[1, 2, 3], [4, 4, 5]])

tensor([[1, 2, 3],
        [4, 4, 5]])

## Using arange

In [11]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

## Using Linespace

In [12]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

## Using Eye

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Using Full

In [14]:
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tansor Shape

In [15]:
x = torch.tensor([[1, 2, 3], [4, 4, 5]])
x

tensor([[1, 2, 3],
        [4, 4, 5]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
# Create Same shape Tensor
# It's takes Random value as store perticular space on hard drive
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor Data Types

In [21]:
x.dtype

torch.int64

## Asign Data Type

In [22]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

tensor([1., 2., 3.])