In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('Dataset/Data.csv')

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [4]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train Test split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [7]:
x_train

array([[-0.51286614,  2.46535459, -0.58538454, ..., -1.7690603 ,
        -0.78802217, -0.89306235],
       [ 1.58514352,  0.43108084,  1.57142489, ...,  1.97006297,
         1.13473816,  0.20763883],
       [ 0.18552791,  1.40389294,  0.12343377, ..., -0.08414673,
        -0.28816836, -0.77671032],
       ...,
       [ 1.44376821, -0.8076799 ,  1.41965245, ...,  0.96526976,
        -0.73372495, -1.16181917],
       [ 0.87826695,  0.62237723,  0.81666465, ...,  1.28378767,
         0.50073829, -0.44131055],
       [ 0.83019935,  1.06795783,  0.86588814, ...,  1.07298113,
         1.00218907,  0.05687281]])

In [8]:
x_test

array([[-0.29232065, -1.29758527, -0.36839097, ..., -1.2255795 ,
        -1.27030923, -0.98210171],
       [ 0.0893927 ,  1.77015554,  0.0229358 , ..., -0.91306265,
        -0.8902287 , -1.04546713],
       [ 1.74631138,  0.84633397,  1.66987188, ...,  0.65136806,
         1.25610842, -0.00540011],
       ...,
       [-0.11984277, -0.99197763, -0.14032212, ..., -0.14723481,
         0.77382136,  0.68834208],
       [-1.5514092 , -0.18713309, -1.54237131, ..., -1.7690603 ,
         0.38256199, -0.14305604],
       [ 1.29391038, -0.53239973,  1.21865652, ...,  0.80678018,
        -0.01348831,  0.04267022]])

In [9]:
y_train

473    B
2      M
542    B
513    B
166    B
      ..
341    B
556    B
161    M
264    M
32     M
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,

In [12]:
y_test

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1])

### Numpy array to pytorch Tensors

In [13]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
x_train_tensor.size()

torch.Size([455, 30])

In [15]:
y_train_tensor.size()

torch.Size([455])

## Defining The model

In [16]:
# we have 30 columns so in our Nueral network there is 30 Weights and one bias
class mySimpleNN():
    def __init__(self, X):
        # indirectly we are take randome value of (30, 1)
        self.weights = torch.rand((X.shape[1], 1), dtype=torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad = True)

    def forward(self, X):
        z = torch.matmul(X, self.weights)  + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # Clamp Prediction to Avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

### Important Parameters

In [17]:
learning_rate = 0.1
epochs = 1

## Training Pipeline

In [18]:
# create model
# here we looks it's 30 rows and columns
model = mySimpleNN(x_train_tensor)
model.weights

tensor([[0.7176],
        [0.1969],
        [0.0217],
        [0.1728],
        [0.9532],
        [0.5232],
        [0.3909],
        [0.2541],
        [0.8016],
        [0.3643],
        [0.6890],
        [0.0505],
        [0.4615],
        [0.3261],
        [0.4148],
        [0.5806],
        [0.2743],
        [0.4152],
        [0.2678],
        [0.2769],
        [0.2896],
        [0.1687],
        [0.3573],
        [0.1864],
        [0.8822],
        [0.1448],
        [0.2205],
        [0.1042],
        [0.8421],
        [0.9957]], dtype=torch.float64, requires_grad=True)

In [19]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

## We do Step by step it
- ### Create Model
- ### Define Loop
- ### forward pass
- ### loss calculate
- ### backward pass
- ### Parameters Update

In [20]:
# create model
model = mySimpleNN(x_train_tensor)

# define Loop
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(x_train_tensor)