In [1]:
import torch

In [2]:
!nvidia-smi

Wed Feb  4 23:25:09 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.32                 Driver Version: 581.32         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   55C    P5             15W /   25W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# Scallar
scallar = torch.tensor(7)
scallar

tensor(7)

In [4]:
scallar.ndim

0

In [5]:
# Get tensor back as python
scallar.item()

7

In [6]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [7]:
TENSOR.ndim

3

In [8]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [9]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.5952, 0.9635, 0.0621, 0.6171],
         [0.5256, 0.1927, 0.7571, 0.4287],
         [0.6844, 0.1158, 0.0400, 0.8327]],

        [[0.3897, 0.2583, 0.4823, 0.3636],
         [0.7539, 0.0237, 0.1744, 0.4354],
         [0.0717, 0.7324, 0.8795, 0.6733]]])

In [10]:
random_tensor.ndim

3

In [11]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channel(r, g, b), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [12]:
# Create Tensors with all Zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
zeros.dtype

torch.float32

In [14]:
# Create Tensors with all Ones
zeros = torch.ones(3, 4)
zeros

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
# Create Tensors with Custome Value
custom = torch.full((3, 4), 5)
custom

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [16]:
torch.range(0, 10)

C:\Users\luxlu\AppData\Local\Temp\ipykernel_5556\1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
one_to_ten = torch.arange(start = 0, end = 1000, step=99)
one_to_ten

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [19]:
# Create Tesnors Like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# Tensor Datatype
float_32_types = torch.tensor([3.0, 6.2, 9.0], dtype=int, device='cpu')
float_32_types.dtype

torch.int64

In [21]:
print(f'Device Tensor is on: {float_32_types.device}')

Device Tensor is on: cpu


In [22]:
# Create Tensor and Add 10 to it
tensor = torch.tensor([2, 3, 4])
print(tensor)
tensor + 10

tensor([2, 3, 4])


tensor([12, 13, 14])

In [23]:
# We just same goes to add, div, sub, mul

In [24]:
print(torch.add(tensor, 2))
print(torch.sub(tensor, 2))
print(torch.mul(tensor, 2))
print(torch.div(tensor, 2))

tensor([4, 5, 6])
tensor([0, 1, 2])
tensor([4, 6, 8])
tensor([1.0000, 1.5000, 2.0000])


### Matrix Multiplication

Two main ways of performing multiplication in nueral networks and deep learning:
1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

## There are two main rules that performing matrix multiplication needs to satisfy:

1. The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

In [25]:
# Element wise multiplication
print(tensor, "*", tensor)
print(tensor * tensor)

tensor([2, 3, 4]) * tensor([2, 3, 4])
tensor([ 4,  9, 16])


In [26]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(29)

In [27]:
tensor @ tensor

tensor(29)

In [28]:
abc = torch.tensor([8, 11, 2])

In [29]:
abc @ abc

tensor(189)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [30]:
tensor.T

C:\Users\luxlu\AppData\Local\Temp\ipykernel_5556\2861277930.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3687.)
  tensor.T


tensor([2, 3, 4])

In [31]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(tensor_A.shape)
tensor_B = torch.tensor([
    [7,  8],
    [9, 10],
    [11, 12]
])

print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [32]:
tensor_B.T.shape

torch.Size([2, 3])

In [33]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


## Aggrigation

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [34]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [35]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [36]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [37]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [38]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding Positional Min and Max

In [39]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value accurs
x.argmin()
# Here it return 0 mean on 0 index there is minimum value

tensor(0)

In [41]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping – reshapes an input tensor to a defined shape

* View – Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking – combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze – removes all `1` dimensions from a tensor

* Unsqueeze – add a `1` dimension to a target tensor

* Permute – Return a view of the input with dimensions permuted (swapped) in a certain way

In [42]:
x = torch.arange(12)

In [43]:
x.reshape(3, 4)     # (12,) → (3,4)
x.reshape(2, 6)     # (12,) → (2,6)
x.reshape(4, 3)     # (12,) → (4,3)
x.reshape(1, 12)    # (12,) → (1,12)
x.reshape(-1, 3)    # auto-calc rows → (4,3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [44]:
x.view(3, 4)
x.view(2, 6)
x.view(4, 3)
x.view(1, 12)
x.view(-1, 2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [45]:
x.is_contiguous()

True

In [46]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

In [47]:
torch.stack([a, b])         # new dimension → (2,2)

tensor([[1, 2],
        [3, 4]])

In [48]:
torch.vstack([a, b])        # vertical stack

tensor([[1, 2],
        [3, 4]])

In [49]:
torch.hstack([a, b])        # horizontal stack

tensor([1, 2, 3, 4])

In [50]:
torch.stack([a, b], dim=1)  # stack along dim=1

tensor([[1, 3],
        [2, 4]])

In [51]:
torch.cat([a, b])           # concat (no new dim)

tensor([1, 2, 3, 4])

In [52]:
x = torch.tensor([[[1, 2, 3]]])

In [53]:
x.squeeze()        # remove all 1s → (3,)

tensor([1, 2, 3])

In [54]:
x.squeeze(0)       # remove dim 0

tensor([[1, 2, 3]])

In [55]:
x.squeeze(1)       # remove dim 1

tensor([[1, 2, 3]])

In [56]:
x.unsqueeze(0).squeeze()

tensor([1, 2, 3])

In [57]:
torch.randn(1, 3, 1).squeeze()

tensor([-1.7872,  0.1561, -0.9038])

In [58]:
x.unsqueeze(0)     # (3,) → (1,3)

tensor([[[[1, 2, 3]]]])

In [59]:
x.unsqueeze(1)     # (3,) → (3,1)

tensor([[[[1, 2, 3]]]])

In [60]:
x.unsqueeze(-1)    # last dim

tensor([[[[1],
          [2],
          [3]]]])

In [61]:
torch.unsqueeze(x, 0)

tensor([[[[1, 2, 3]]]])

In [62]:
x.view(1, -1)

tensor([[1, 2, 3]])

In [63]:
x = torch.randn(2, 3, 4)

In [64]:
x.permute(1, 0, 2)   # swap dim 0 & 1

tensor([[[ 0.4612,  1.2630, -0.4801,  0.8620],
         [ 2.0693,  1.3749, -1.3788, -0.5420]],

        [[-0.0659, -0.1291, -2.1920, -1.1285],
         [-1.1938, -0.1667, -0.4730, -0.5035]],

        [[ 0.6974,  0.6823,  0.6865, -0.2891],
         [ 0.9294, -0.2170, -0.6749, -1.6859]]])

In [65]:
x.permute(2, 1, 0)

tensor([[[ 0.4612,  2.0693],
         [-0.0659, -1.1938],
         [ 0.6974,  0.9294]],

        [[ 1.2630,  1.3749],
         [-0.1291, -0.1667],
         [ 0.6823, -0.2170]],

        [[-0.4801, -1.3788],
         [-2.1920, -0.4730],
         [ 0.6865, -0.6749]],

        [[ 0.8620, -0.5420],
         [-1.1285, -0.5035],
         [-0.2891, -1.6859]]])

In [66]:
x.permute(0, 2, 1)

tensor([[[ 0.4612, -0.0659,  0.6974],
         [ 1.2630, -0.1291,  0.6823],
         [-0.4801, -2.1920,  0.6865],
         [ 0.8620, -1.1285, -0.2891]],

        [[ 2.0693, -1.1938,  0.9294],
         [ 1.3749, -0.1667, -0.2170],
         [-1.3788, -0.4730, -0.6749],
         [-0.5420, -0.5035, -1.6859]]])

In [67]:
x.permute(2, 0, 1)

tensor([[[ 0.4612, -0.0659,  0.6974],
         [ 2.0693, -1.1938,  0.9294]],

        [[ 1.2630, -0.1291,  0.6823],
         [ 1.3749, -0.1667, -0.2170]],

        [[-0.4801, -2.1920,  0.6865],
         [-1.3788, -0.4730, -0.6749]],

        [[ 0.8620, -1.1285, -0.2891],
         [-0.5420, -0.5035, -1.6859]]])

In [68]:
x.permute(1, 2, 0)

tensor([[[ 0.4612,  2.0693],
         [ 1.2630,  1.3749],
         [-0.4801, -1.3788],
         [ 0.8620, -0.5420]],

        [[-0.0659, -1.1938],
         [-0.1291, -0.1667],
         [-2.1920, -0.4730],
         [-1.1285, -0.5035]],

        [[ 0.6974,  0.9294],
         [ 0.6823, -0.2170],
         [ 0.6865, -0.6749],
         [-0.2891, -1.6859]]])

# Indexing

In [69]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:

x[0][1:][:1]

tensor([[4, 5, 6]])

In [72]:
x[0, 2, 1]

tensor(8)

In [73]:
# Numpy to Tensor
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)

In [74]:
tensor.dtype

torch.float32

In [75]:
# Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed **

Essentially what the random seed does is "Flavour" the randomness

In [76]:
torch.manual_seed(5)
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(5)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A == random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Getting a GPU

In [77]:
torch.cuda.is_available()

True

In [78]:
!nvidia-smi

Wed Feb  4 23:25:11 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.32                 Driver Version: 581.32         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   55C    P5             15W /   25W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [79]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1


In [80]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [81]:
import torch

print("Torch version:", torch.__version__)
print("CUDA compiled version:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())


Torch version: 2.5.1+cu121
CUDA compiled version: 12.1
CUDA available: True


In [82]:
print(torch.cuda.get_device_name(0))

NVIDIA GeForce RTX 3050 6GB Laptop GPU


In [83]:
import platform
print(platform.processor())

Intel64 Family 6 Model 183 Stepping 1, GenuineIntel


In [84]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
torch.set_default_device(device)

In [85]:
torch.cuda.device_count()

1

In [86]:
## Putting tensors (add models) on the GPU

# Create a Tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Create a Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [87]:
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [88]:
test = tensor_on_gpu.cpu()
print(test, test.device)

tensor([1, 2, 3]) cpu


In [89]:
test = tensor_on_gpu.cuda()
print(test, test.device)

tensor([1, 2, 3], device='cuda:0') cuda:0
