In [1]:
import torch

In [2]:
!nvidia-smi

Wed Jan 28 12:15:53 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.32                 Driver Version: 581.32         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P0             14W /   85W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# Scallar
scallar = torch.tensor(7)
scallar

tensor(7)

In [4]:
scallar.ndim

0

In [5]:
# Get tensor back as python
scallar.item()

7

In [6]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [7]:
TENSOR.ndim

3

In [8]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [9]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.9464, 0.1202, 0.5096, 0.7980],
         [0.0578, 0.0365, 0.1252, 0.1690],
         [0.6638, 0.1744, 0.8469, 0.1925]],

        [[0.9455, 0.7850, 0.8070, 0.5123],
         [0.8002, 0.6054, 0.9818, 0.4973],
         [0.1195, 0.5684, 0.4403, 0.6994]]])

In [10]:
random_tensor.ndim

3

In [11]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channel(r, g, b), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [12]:
# Create Tensors with all Zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
zeros.dtype

torch.float32

In [14]:
# Create Tensors with all Ones
zeros = torch.ones(3, 4)
zeros

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
# Create Tensors with Custome Value
custom = torch.full((3, 4), 5)
custom

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [16]:
torch.range(0, 10)

C:\Users\luxlu\AppData\Local\Temp\ipykernel_25412\1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
one_to_ten = torch.arange(start = 0, end = 1000, step=99)
one_to_ten

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [19]:
# Create Tesnors Like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# Tensor Datatype
float_32_types = torch.tensor([3.0, 6.2, 9.0], dtype=int, device='cpu')
float_32_types.dtype

torch.int64

In [21]:
print(f'Device Tensor is on: {float_32_types.device}')

Device Tensor is on: cpu


In [22]:
# Create Tensor and Add 10 to it
tensor = torch.tensor([2, 3, 4])
print(tensor)
tensor + 10

tensor([2, 3, 4])


tensor([12, 13, 14])

In [23]:
# We just same goes to add, div, sub, mul

In [24]:
print(torch.add(tensor, 2))
print(torch.sub(tensor, 2))
print(torch.mul(tensor, 2))
print(torch.div(tensor, 2))

tensor([4, 5, 6])
tensor([0, 1, 2])
tensor([4, 6, 8])
tensor([1.0000, 1.5000, 2.0000])


### Matrix Multiplication

Two main ways of performing multiplication in nueral networks and deep learning:
1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

## There are two main rules that performing matrix multiplication needs to satisfy:

1. The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

In [25]:
# Element wise multiplication
print(tensor, "*", tensor)
print(tensor * tensor)

tensor([2, 3, 4]) * tensor([2, 3, 4])
tensor([ 4,  9, 16])


In [26]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(29)

In [27]:
tensor @ tensor

tensor(29)

In [28]:
abc = torch.tensor([8, 11, 2])

In [29]:
abc @ abc

tensor(189)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [30]:
tensor.T

C:\Users\luxlu\AppData\Local\Temp\ipykernel_25412\2861277930.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4419.)
  tensor.T


tensor([2, 3, 4])

In [31]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(tensor_A.shape)
tensor_B = torch.tensor([
    [7,  8],
    [9, 10],
    [11, 12]
])

print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [32]:
tensor_B.T.shape

torch.Size([2, 3])

In [33]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])
